version: '3.4'

services:
  db:
    image: postgres
    restart: always
    container_name: wisdo_db
    environment:
      POSTGRES_PASSWORD: wisdo
      POSTGRES_USER: wisdo
      POSTGRES_DB: wisdo
  app:
    container_name: wisdo_app
    build: .
    depends_on: 
      - db
    ports:
      - 80:80
    environment:
      DB_NAME: wisdo
      DB_USER: wisdo
      DB_PASS: wisdo
      DB_HOST: wisdo_db
      PORT: 80
    volumes: 
      - .:/usr/src/app
  adminer:
    image: adminer
    container_name: wisdo_db_admin
    restart: always
    ports:
      - 8080:8080